eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8090
spring:
  application:
    name: service-zuul
    
zuul:
  routes:
    article:
      path: /article/**
      serviceId: article
    notice:
      path: /notice/**
      serviceId: SERVER-NOTICE