server:
  port: 8092 # 服务端口

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/ # 服务注册中心地址

spring:
  application:
    name: customer-service # 服务名称
  zipkin: 
    base-url: http://localhost:8087	